server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservationProcesses/** /movieLists/**
        - id: caCenter
          uri: http://localhost:8082
          predicates:
            - Path= 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payProcesses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservationProcesses/** /movieLists/**
        - id: caCenter
          uri: http://caCenter:8080
          predicates:
            - Path= 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payProcesses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
